export enum Types {
      USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
      USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
      USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
      USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED',
      USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION',
      COMPANIES_FETCH_SUCCESS = 'COMPANIES_FETCH_SUCCESS',
      COMPANIES_FETCH_FAILED = 'COMPANIES_FETCH_FAILED'
}