export enum Types {
      USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
      USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
      USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
      USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED',
      USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION',
      POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS',
      POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED',
      COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS',
      COMMENTS_FETCH_FAILED = 'COMMENTS_FETCH_FAILED'
}